version: 2
jobs:
  build:
    docker:
      - image: alpine:3.5
    working_directory: /home/circleci/blog
    steps:
      - setup_remote_docker:
          # https://circleci.com/docs/2.0/docker-layer-caching/
          reusable: true
      - run:
          name: Install System Dependencies
          command: |
            # https://circleci.com/docs/2.0/custom-images/#required-tools
            apk add --update --no-cache git openssh tar gzip ca-certificates
      - run:
          name: Install Docker client
          command: |
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - checkout
      - run:
          name: Init git submodules
          command: git submodule sync && git submodule update --init --recursive
      - run:
          name: Build tsub/blog image
          command: sh bin/build
      - run:
          name: Test tsub/blog image
          command: |
            docker run -d --name blog tsub/blog
            docker run --network container:blog appropriate/curl --retry 10 --retry-connrefused http://localhost/healthz
      - deploy:
          name: Deploy tsub/blog image
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              bin/deploy
              bin/deploy $CIRCLE_TAG
            fi
