version: '3'
services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile-hugo
    command: [server, --bind=0.0.0.0]
    container_name: hugo
    image: tsub/blog:hugo
    ports:
      - 1313:1313
    volumes:
      - .:/app
