version: 2
jobs:
  build:
    docker: &docker
      - image: docker:17.03-git
    working_directory: /home/circleci/blog
    steps:
      - setup_remote_docker: &setup_remote_docker
          # ref: https://circleci.com/docs/2.0/docker-layer-caching/
          reusable: true
      - run: &install_system_dependencies
          name: Install System Dependencies
          command: |
            # ref: https://circleci.com/docs/2.0/custom-images/#required-tools
            apk add --update --no-cache openssh tar gzip ca-certificates
      - checkout
      - run:
          name: Init git submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: Build tsub/blog image
          command: |
            bin/build
            docker save tsub/blog:latest -o blog.tar
      - persist_to_workspace:
          root: /home/circleci/blog
          paths:
            - themes
            - blog.tar

  test:
    docker: *docker
    working_directory: /home/circleci/blog
    steps:
      - setup_remote_docker: *setup_remote_docker
      - run: *install_system_dependencies
      - checkout
      - attach_workspace: &attach_workspace
          at: /home/circleci/blog
      - run: &load_docker_image
          name: Load docker image
          command: docker load -i blog.tar
      - run:
          name: Test tsub/blog image
          command: |
            docker run -d --name blog tsub/blog
            docker run --network container:blog appropriate/curl --retry 10 --retry-connrefused http://localhost

  deploy:
    docker: *docker
    working_directory: /home/circleci/blog
    steps:
      - setup_remote_docker: *setup_remote_docker
      - run: *install_system_dependencies
      - checkout
      - attach_workspace: *attach_workspace
      - run: *load_docker_image
      - deploy:
          name: Deploy tsub/blog image
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

            # Deploy tsub/blog:latest image
            bin/deploy

            # Deploy tsub/blog:$CIRCLE_TAG image
            bin/deploy $CIRCLE_TAG

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
