version: 2
jobs:
  build:
    docker: &docker
      - image: docker:17.06-git
    working_directory: /home/circleci/blog
    steps:
      - setup_remote_docker: &setup_remote_docker
          # ref: https://circleci.com/docs/2.0/docker-layer-caching/
          reusable: true
          version: 17.06.0-ce
      - run: &install_system_dependencies
          name: Install System Dependencies
          command: |
            # ref: https://circleci.com/docs/2.0/custom-images/#required-tools
            apk add --update --no-cache openssh tar gzip ca-certificates
      - checkout
      - run:
          name: Init git submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: Build tsub/blog image
          command: |
            bin/build
            docker save tsub/blog:latest -o blog.tar
      - persist_to_workspace:
          root: /home/circleci/blog
          paths:
            - themes
            - blog.tar

  deploy:
    docker: *docker
    working_directory: /home/circleci/blog
    steps:
      - setup_remote_docker: *setup_remote_docker
      - run: *install_system_dependencies
      - checkout
      - attach_workspace:
          at: /home/circleci/blog
      - run:
          name: Load docker image
          command: docker load -i blog.tar
      - deploy:
          name: Deploy tsub/blog image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            # Deploy tsub/blog:latest image
            bin/deploy

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
