version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: docker:17.06-git
    working_directory: /home/circleci/blog
    steps:
      - setup_remote_docker:
          # ref: https://circleci.com/docs/2.0/docker-layer-caching/
          reusable: true
          version: 17.06.0-ce
      - run:
          name: Install System Dependencies
          command: |
            # ref: https://circleci.com/docs/2.0/custom-images/#required-tools
            apk add --update --no-cache openssh tar gzip ca-certificates
      - checkout
      - deploy:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email $GIT_USER_EMAIL
            git config --global user.name $GIT_USER_NAME

            bin/deploy
